# This is a basic workflow to help you get started with Actions

name: saltpeter-ui-npm

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # npm clean cache
      - name: npm-clean-cache
        run: npm cache clean --force
        
      # delete modules folder
      - name: delete-modules-folder
        run: rm -rf node_modules package-lock.jsonl
        
      # npm install
      - name: npm-install-cmd
        run: npm install

      # npm run build
      - name: npm-run-build-cmd
        run: npm run build
